<template>
    <section id="music" class="bg-base-200 min-h-[100dvh] py-16 md:px-48 px-4">
        <h1 class="md:text-5xl text-4xl font-semibold text-center text-base-content/90 font-serif mb-16 uppercase">Music</h1>
        <div class="w-full h-full flex flex-wrap justify-between gap-y-10">
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/kX4J4ZfNBmA?si=XwNHV3DpQpe3Ab2Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/m0HTztWfoLg?si=YKpmD042z0PbKi32" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>            
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/0Mi6X-9c6q4?si=3HvD-kr17NYIyOGN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>           
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/e9UpSuymNGc?si=jeJM6VApOksVQA7W" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/FY325zI4dWg?si=hSC_KeAYFmx2tulR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/3qSvh7ebJeA?si=sSWM8zPCTlY4IZI4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/NjH8lDQxoQQ?si=HGeN1CIrpCDoUL1F" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/U0tuVUkmr0k?si=BOuMUR-9QzM1Fy_J" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/9oRQk3gBKQQ?si=gbDdCqjmqTZ58wzw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/M4daw97UHi4?si=Ip-t0z_1VVFEGdO_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/M1KBWrrm7rY?si=9-a8CnNh9LUSbNjD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            <iframe class="lg:w-[30%] md:w-[47%] w-full h-[30dvh] " src="https://www.youtube.com/embed/PxuLmhyuX84?si=rNmUq762JM3zf5Fj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
           
           
            <!-- <iframe class="md:w-[440px] md:h-[248px]" src="https://www.youtube.com/embed/aX-f1nMUj-8?si=o1HBM-mIZAkWE9cK" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe> -->
        </div>
        </section>
</template>